# Домашнее задание по методу Ньютона и квазиньютоновским методам

##### Выполнил: АРТЁМ АГАФОНОВ

##### Баллов:   /30

В этом задании Вам предлагается погрузиться в специфику тестирования алгоритмов оптимизации на одинаковых классах задач на примере метода Ньютона и квазиньютоновских методов.

## Теория (10)
Приведем стандартные обозначения.

### Метод Ньютона:
$$
x_{k+1} = x_k - \left[ f_{xx}(x_k)\right]^{-1}\nabla f(x_k) = x_k - \left[ B(x_k)\right]^{-1}\nabla f(x_k) = x_k - H(x_k)\nabla f(x_k)
$$

### SR-1 (symmetric rank one) update
для квазиньютоновского метода использует следующую формулу для уточнения **обратного** гессиана:

$$
H_{k+1} = H_k + \dfrac{(\Delta x_k - H_k \Delta y_k)(\Delta x_k - H_k \Delta y_k)^\top}{\langle \Delta x_k - H_k \Delta y_k , \Delta y_k\rangle},  \quad \Delta y_k = \nabla f(x_{k+1}) - \nabla f(x_k), \quad \Delta x_k = x_{k+1} - x_k
$$

$$
x_{k+1} = x_k - H_k \nabla f (x_k)
$$

Оценка гессиана при этом:

$$
B_{k+1}=B_{k}+\frac {(\Delta y_k-B_k \Delta x_k) (\Delta y_k-B_k \Delta x_k)^\top}{(\Delta y_k-B_k \Delta x_k)^\top \Delta x_k}
$$

### BFGS
использует следующую формулу для уточнения **обратного** гессиана:
$$
H_{k+1} = H_k + \frac{(\Delta x_k^{\top}\Delta y_k+\Delta y_k^{\top}  H_k \Delta y_k)(\Delta x_k \Delta x_k^{\top})}{(\Delta x_k^{\top} \Delta y_k)^2} - \frac{ H_k \Delta y_k \Delta x_k^{\top} + \Delta x_k \Delta y_k^{\top} H_k}{\Delta x_k^{\top} \Delta y_k}.
$$
Оценка гессиана при этом:

$$
B_{k+1} = B_k + \frac{\Delta y_k \Delta y_k^{\top}}{\Delta y_k^{\top} \Delta x_k} - \frac{B_k \Delta x_k \Delta x_k^{\top} B_k^{\top} }{\Delta x_k^{\top} B_k \Delta x_k}
$$


Докажите, что для метода Ньютона обладает афинной инвариантностью, т.е. если есть преобразование координат $\tilde{f}(z) = f(x)$, где $x = Sz + s, \;\; s \in \mathbb{R}^n, S \in \mathbb{R}^{n \times n}$, то будет выполняться:

$$
\nabla \tilde{f}(z) = S^\top \nabla f(x), \qquad \nabla^2 \tilde{f}(z) = S^\top \nabla^2 f(x) S
$$

Покажите так же, что метод Ньютона и описанные выше оба квазиньютоновских метода запущенные независимо по координатам $x$ и $z$ будут работать так, что всегда будет выполняться связь $x_k = Sz_k + s$, если $x_0 = Sz_0 + s$ и инициализацией $B_0$ для метода по координате $x$ и $S^\top B_0 S$ для координаты $z$

### Решение:
1. Докажем, что $\nabla \tilde{f}(z) = f(x) \Rightarrow  \nabla \tilde{f}(z) = S^\top \nabla f(x)$. 

$d\tilde{f}(z) = \langle \tilde f(z), dz \rangle$;

$df(x) = \langle \nabla f(x), dx \rangle = \langle \nabla f(x), Sdz \rangle$.

$d \tilde{f}(z) = d f(x) \Rightarrow \langle \nabla \tilde f(z), dz \rangle = \langle \nabla f(x), Sdz\rangle \Rightarrow dz^T\nabla\tilde{f}(z) = dz^TS^T\nabla f(x) \Rightarrow$ 
$$\Rightarrow \nabla \tilde{f}(z) = S^T \nabla f(x).$$

2. Докажем, что $\nabla \tilde{f}(z) = f(x) \Rightarrow  \nabla^2 \tilde{f}(z) = S^\top \nabla^2 f(x) S$.

$d^2\tilde{f}(z) = \langle \nabla^2 \tilde{f}(z)dz_1, dz_2\rangle$;

$d^2 f(x) = \langle \nabla^2 f(x) dx_1, dx_2 \rangle = \langle \nabla^2 f(x) Sdz_1, Sdz_2 \rangle$.

$d^2 \tilde{f}(z) = d^2 f(x) \Rightarrow dz_1^T \nabla^2 \tilde{f}(z) dz_2 = dz_1^TS^T\nabla^2f(x)^TSdz_2 \Rightarrow$

$$\Rightarrow \nabla^2 \tilde{f}(z) = S^\top \nabla^2 f(x) S.$$

3. Докажем, что метод Ньютона афинно инвариантен. Воспользуемся мат. индукцией: $x_0 = Sz_0 + s$ база доказана. Пусть верно для $k$, докажем что верно для $k+1$.

$x_{k+1} = x_k - [\nabla^2 f(x_k)]^{-1}\nabla f(x_k)$;

$z_{k+1} = z_k - [\nabla^2 \tilde{f}(z_k)^{-1}]^{-1} \nabla \tilde{f}(z_k)$.

Воспользуемся предыдущими пунктами и распишем метод Ньютона для функции $\tilde{f}(z)$:

$z_{k+1} = z_k - [S^T\nabla^2f(x_k)S]^{-1}S^T\nabla f(x_k) = S^{-1}(x_k-s) - S^{-1}[\nabla^2 f(x_k)]^{-1}\nabla f(x_k) = S^{-1} (x_k - s - [\nabla^2 f(x_k)]^{-1}\nabla f(x_k)) = S^{-1}[x_{k+1} - s] \Rightarrow$
$$ \Rightarrow Sz_{k+1} + s = x_{k+1}.$$

4. Докажем, что квазиньютоновский метод SR-1 афинно инвариантен. Воспользуемся мат. индукцией: $x_0 = Sz_0 + s$ и $\tilde{B_0} = S^TBS$ база доказана. Пусть верно для $k$, что $\tilde{B_k} = S^T\tilde{B}_kS$ и для любого $i \in \mathbb{N}$ меньшего $k+1$, что $x_i = Sz_i + s$, докажем, что из этого следует верность утверждений для $k+1$.

$B_{k+1}=B_{k}+\dfrac {(\Delta y_k-B_k \Delta x_k) (\Delta y_k-B_k \Delta x_k)^\top}{(\Delta y_k-B_k \Delta x_k)^\top \Delta x_k}$

$\tilde{B}_{k+1}= \tilde{B_{k}}+\dfrac {(\Delta \tilde{y_k}-\tilde{B_k} \Delta z_k) (\Delta \tilde{y_k}-\tilde{B_k} \Delta z_k)^\top}{(\Delta \tilde{y_k}-\tilde{B_k} \Delta z_k)^\top \Delta z_k}$, где $\Delta \tilde{y}_k = \nabla \tilde{f}(z_{k+1}) - \tilde{f}(z_K) = S^T\Delta y_k$ и $\Delta z_k = z_{k+1} - z_k = S^{-1}\Delta x_k$.

Воспользуемся предыдущими пунктами и распишем SR-1 для функции $\tilde{f}(z)$:
$ \tilde{B}_{k+1} = S^TB_kS + \dfrac{(S^T\Delta y_k - S^TB_kSS^{-1}\Delta x_k)(S^T\Delta y_k - S^TB_kSS^{-1}\Delta x_k)^T}{(S^T\Delta y_k - S^TB_kSS^{-1}\Delta x_k)^T S^{-1}\Delta x_k} = 
S^TB_kS + \dfrac{S^T(\Delta y_k - B_k\Delta x_k)(\Delta y_k - B_k\Delta x_k)^TS}{(\Delta y_k - S^TB_kSS^{-1}\Delta x_k)^T SS^{-1}\Delta x_k} = S^T[B_{k}+\dfrac {(\Delta y_k-B_k \Delta x_k) (\Delta y_k-B_k \Delta x_k)^\top}{(\Delta y_k-B_k \Delta x_k)^\top \Delta x_k}]S = S^T B_{k+1} S$

Пока что мы доказали лишь половину задачи, а именно, что $\tilde{B_k} = S^T\tilde{B}_kS$ для любого $k \in \mathbb{N}$. Теперь докажем вторую часть задачи: $x_{k+2} = Sz_{k+2} + s$.

$x_{k+2} = x_{k+1} - [B_{k+1}]^{-1}\nabla f(x_{k+1})$;

$z_{k+2} = z_{k+1} - [\tilde{B}_{k+1})^{-1}]^{-1} \nabla \tilde{f}(z_{k+1}) = S^{-1}(x_{k+1} - s) - [S^TB_{k+1}S]^{-1}[S^T\nabla f(x)] = S^{-1}[x_{k_1} - s - B_{k+1}^{-1}(S^T)^{-1}S^T\nabla f(x)] = S^{-1}[x_{k+2} - x] \Rightarrow$
$$\Rightarrow x_{k+2} = Sz_{k+2} + s.$$
5. Докажем, что квазиньютоновский метод BFGS афинно инвариантен. Воспользуемся мат. индукцией: $x_0 = Sz_0 + s$ и $\tilde{B_0} = S^TBS$ база доказана. Пусть верно для $k$, что $\tilde{B_k} = S^T\tilde{B}_kS$ и для любого $i \in \mathbb{N}$ меньшего $k+1$, что $x_i = Sz_i + s$, докажем, что из этого следует верность утверждений для $k+1$.

$
B_{k+1} = B_k + \dfrac{\Delta y_k \Delta y_k^{\top}}{\Delta y_k^{\top} \Delta x_k} - \dfrac{B_k \Delta x_k \Delta x_k^{\top} B_k^{\top} }{\Delta x_k^{\top} B_k \Delta x_k}
$

$
\tilde{B}_{k+1} = \tilde{B}_k + \dfrac{\Delta \tilde{y_k} \Delta \tilde{y_k}^{\top}}{\Delta \tilde{y_k}^{\top} \Delta z_k} - \dfrac{\tilde{B}_k \Delta z_k \Delta z_k^{\top} \tilde{B}_k^{\top} }{\Delta z_k^{\top} \tilde{B}_k \Delta z_k}
$, где $\Delta \tilde{y}_k = \nabla \tilde{f}(z_{k+1}) - \tilde{f}(z_K) = S^T\Delta y_k$ и $\Delta z_k = z_{k+1} - z_k = S^{-1}\Delta x_k$.

$\tilde{B}_{k+1} = S^TB_kS + \dfrac{S^T\Delta y_k (S^T\Delta y_k)^T}{(S^T\Delta y_k)^T S^{-1}\Delta x_k} - \dfrac{S^TB_kS  S^{-1}\Delta x_k (S^{-1}\Delta x_k)^{\top} (S^TB_kS)^{\top} }{(S^{-1}\Delta x_k)^{\top} S^TB_kS S^{-1}\Delta x_k} = S^T[B_k + \dfrac{\Delta y_k \Delta y_k^{\top}}{\Delta y_k^{\top} \Delta x_k} - \dfrac{B_k \Delta x_k \Delta x_k^{\top} B_k^{\top} }{\Delta x_k^{\top} B_k \Delta x_k}] = S^T B_{k+1} S$.

Пока что мы доказали лишь половину задачи, а именно, что $\tilde{B_k} = S^T\tilde{B}_kS$ для любого $k \in \mathbb{N}$. Вторая же часть задачи доказывается аналогично предыдущему пункту. 


## Практика (20)
Реализуйте на языке python:
* метод Ньютона
* метод SR-1

для минимизации следующих функций:
* Квадратичная форма $f(x) = \dfrac{1}{2}x^\top A x + b^\top x, \quad x \in \mathbb{R}^n, A \in \mathbb{R}^{n \times n}$. Попробуйте n = 2, 50, 228
* Функция Розенброка $f(x, y) = (1-x)^2 + 100(y-x^2)^2 .\quad$

Сравните 2 реализованных Вами метода И [метод](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-bfgs.html) `BFGS` из библиотеки `scipy`, а так же его модификацию [L-BFGS](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) в решении задачи минимизации описанных выше функций. точку старта необходимо инициализировать одинаковую для всех методов в рамках одного запуска. Необходимо провести не менее 10 запусков для каждого метода на каждой функции до достижения того критерия остановки, который вы выберете (например, расстояние до точки оптимума - во всех задачах мы её знаем)

В качестве результата нужно заполнить следующие таблички, заполнив в них усредненное по числу запусков количество итераций, необходимых для сходимости и времени работы:

Критерий остановки `невязка по аргументу`

Число запусков `10`

P.S. если в силу каких то причин Вам не удалось сделать задание полностью, попробуйте сфокусироваться хотя бы на его части.

| Квадратичная форма. n = 2 | Iterations | Time |
|:-------------------------:|:----------:|:----:|
|           Newton          |    11      | 0.00202457905      |
|            SR-1           |    3       |  0.000395011902     |
|            BFGS           |    3.8     | 0.00107023716   |
|           L-BFGS          |    4.1     |  0.000545954704  |

| Квадратичная форма. n = 50 | Iterations | Time |
|:-------------------------:|:----------:|:----:|
|           Newton          |     15.8     |   0.00342473984   |
|            SR-1           |      24.1      |   0.00403673649   |
|            BFGS           |30.7|  0.0197077036    |
|           L-BFGS          |19.6|0.00233104229|


| Квадратичная форма. n = 228 | Iterations | Time |
|:-------------------------:|:----------:|:----:|
|           Newton          |16.9|0.153806996|
|            SR-1           |56.4|0.139915681|
|            BFGS           |59.4|0.395602679|
|           L-BFGS          |19.9|0.00773038864|

| Функция Розенброка | Iterations | Time |
|:-------------------------:|:----------:|:----:|
|           Newton          |4|0.00042365|
|            SR-1           |66|0.00796235|
|            BFGS           |13.6|0.0033474|
|           L-BFGS          |5.7|0.00065005|

In [333]:
import numpy as np
from scipy.optimize import minimize
import time
import sklearn.datasets

In [353]:
def quad(A, b, x):
    return 0.5 * np.dot(np.dot(np.transpose(x), A), x) + np.dot(np.transpose(b), x)

def quad_grad(A, b, x):
    return 0.5 * np.dot((A + np.transpose(A)), x) + b

def quad_hessian(A, b, x):
    return (A + np.transpose(A))

def rosen(x):
    a, b = x
    return (1 - a)**2 + 100 * (b - a**2)**2

def rosen_grad(x):
    a, b = x
    dx = -2 * (1 - a) - 400 * (b - a**2) * a
    dy = 200 * (b - a**2)
    return np.array([dx, dy])

def rosen_hessian(x):
    a, b = x
    dxx = 2 - 400 * b + 1200 * a**2
    dyy = 200
    dxy = -400 * a
    return np.array([[dxx, dxy],[dxy, dyy]])

In [191]:
def newton_descent(df, ddf, x0, eps, x_sol):
    x = [x0]
    while np.linalg.norm(x[-1] - x_sol) > eps:
        H = np.linalg.inv(ddf(x[-1]))
        x.append(x[-1] - np.dot(H, df(x[-1])))
    return x

In [192]:
def sr1_hessian(dx, dy, H):
    a = dx - np.dot(H, dy)
    return np.outer(a, a)/(np.dot(np.transpose(a), dy))

def sr1(df, x0, eps, x_sol):
    x = [x0]
    H = np.eye(len(x0))
    while np.linalg.norm(x[-1] - x_sol) > eps:
        x.append(x[-1] - np.dot(H, df(x[-1])))
        dx = x[-1] - x[-2]
        dy = df(x[-1]) - df(x[-2])
        H = H + sr1_hessian(dx, dy, H)
    return x

## Квадратичная форма

In [345]:
N = [2, 50, 228]
eps = 1e-3

q_time = np.zeros((3, 4))
q_iter = np.zeros((3, 4))
j = 0
cnt_BFGS = []
cnt_L_BFGS = []
for n in N:
    m = 0
    l = 0
    for i in range(10):
        #A = np.dot(np.random.rand(n,n),
             #np.transpose(np.random.rand(n,n)))
        A = sklearn.datasets.make_spd_matrix(n) #Генерит отличную матрицу, что ее решают методы из 
        #scipy optimize, иначе плохое число обусловленности и они не находят минимум правильно 
        b = np.random.rand(n)
        x_sol = - 2 * np.dot(np.linalg.inv(A + np.transpose(A)), b)
        #x0 = np.random.normal(x_sol, 2, n)
        x0 = np.random.rand(n)
        #print(np.linalg.norm(x_sol - x0))
        _quad = lambda x: quad(A, b, x)
        d_quad = lambda x: quad_grad(A, b, x)
        dd_quad = lambda x: quad_hessian(A, b, x)
        
        
        start = time.time()
        x = newton_descent(d_quad, dd_quad, x0, eps, x_sol)
        end = time.time()
        q_time[j][0] = q_time[j][0] + end - start
        q_iter[j][0] = q_iter[j][0] + len(x) - 1
        
        start = time.time()
        x = sr1(d_quad, x0, eps, x_sol)
        end = time.time()
        q_time[j][1] = q_time[j][1] + end - start
        q_iter[j][1] = q_iter[j][1] + len(x) - 1 
        
        start = time.time()
        x = minimize(_quad, x0, method='BFGS', tol = eps, jac = d_quad)
        end = time.time()
        if x['success'] == True:
            q_time[j][2] = q_time[j][2] + end - start
            q_iter[j][2] = q_iter[j][2] + x['nit'] 
            m = m + 1
        
        start = time.time()
        x = minimize(_quad, x0, method='L-BFGS-B', tol = eps, jac = d_quad)
        end = time.time()
        if x['success'] == True:
            q_time[j][3] = q_time[j][3] + end - start
            q_iter[j][3] = q_iter[j][3] + x['nit'] 
            l = l + 1
    cnt_BFGS.append(m)
    cnt_L_BFGS.append(l)
    j = j + 1

In [346]:
print (cnt_BFGS)
print (cnt_L_BFGS)
print ('TOTAL TIME: Newton, SR1, BFGS, L-BFGS')
print ('n = 2, 50, 228')
print (q_time)
print ('TIME: Newton, SR1, BFGS, L-BFGS')
print ('n = 2, 50, 228')
print (q_time / 10)
print ('TOTAL ITERATIONS: Newton, SR1, BFGS, L-BFGS')
print ('n = 2, 50, 228')
print (q_iter)
print ('ITERATIONS: Newton, SR1, BFGS, L-BFGS')
print ('n = 2, 50, 228')
print (q_iter / 10)

[10, 10, 10]
[10, 10, 10]
TOTAL TIME: Newton, SR1, BFGS, L-BFGS
n = 2, 50, 228
[[2.02457905e-02 3.95011902e-03 1.07023716e-02 5.45954704e-03]
 [3.42473984e-02 4.03673649e-02 1.97077036e-01 2.33104229e-02]
 [1.53806996e+00 1.39915681e+00 3.95602679e+00 7.73038864e-02]]
TIME: Newton, SR1, BFGS, L-BFGS
n = 2, 50, 228
[[2.02457905e-03 3.95011902e-04 1.07023716e-03 5.45954704e-04]
 [3.42473984e-03 4.03673649e-03 1.97077036e-02 2.33104229e-03]
 [1.53806996e-01 1.39915681e-01 3.95602679e-01 7.73038864e-03]]
TOTAL ITERATIONS: Newton, SR1, BFGS, L-BFGS
n = 2, 50, 228
[[110.  30.  38.  41.]
 [158. 241. 307. 196.]
 [169. 564. 594. 199.]]
ITERATIONS: Newton, SR1, BFGS, L-BFGS
n = 2, 50, 228
[[11.   3.   3.8  4.1]
 [15.8 24.1 30.7 19.6]
 [16.9 56.4 59.4 19.9]]


## Розенброк

In [359]:
eps = 1e-3

r_time = np.zeros(4)
r_iter = np.zeros(4)
j = 0
cnt_BFGS = []
cnt_L_BFGS = []
m = 0
l = 0
for i in range(10):
    x_sol = [1, 1]
    x0 = np.random.rand(2)
        
    start = time.time()
    x = newton_descent(rosen_grad, rosen_hessian, x0, eps, x_sol)
    end = time.time()
    r_time[0] = r_time[0] + end - start
    r_iter[0] = r_iter[0] + len(x) - 1
        
    start = time.time()
    x = sr1(rosen_grad, x0, eps, x_sol)
    end = time.time()
    r_time[1] = r_time[1] + end - start
    r_iter[1] = r_iter[1] + len(x) - 1 
        
    start = time.time()
    x = minimize(rosen, x0, method='BFGS', tol = eps, jac = rosen_grad)
    end = time.time()
    if x['success'] == True:
        r_time[2] = r_time[2] + end - start
        r_iter[2] = r_iter[2] + x['nit'] 
        m = m + 1
        
    start = time.time()
    x = minimize(rosen, x0, method='L-BFGS-B', tol = eps, jac = rosen_grad)
    end = time.time()
    if x['success'] == True:
        r_time[3] = r_time[3] + end - start
        r_iter[3] = r_iter[3] + x['nit'] 
        l = l + 1
cnt_BFGS.append(m)
cnt_L_BFGS.append(l)

In [362]:
print(cnt_BFGS)
print(cnt_L_BFGS)
print (r_time)
print (r_time/10)
print (r_iter)
print (r_iter/10)

[10]
[10]
[0.00423646 0.07962346 0.03347397 0.00650048]
[0.00042365 0.00796235 0.0033474  0.00065005]
[ 40. 660. 136.  57.]
[ 4.  66.  13.6  5.7]
